fix: avoid echo usage
Echo can interpret operand as an option and checking every variable to
be echoed is troublesome while with printf, if the format specifier is
present before the operand, printing as string can be enforced.

diff --git a/salt/dom0/files/bin/qvm-mgmt b/salt/dom0/files/bin/qvm-mgmt
--- a/salt/dom0/files/bin/qvm-mgmt
+++ b/salt/dom0/files/bin/qvm-mgmt
@@ -6,7 +6,7 @@
 set -eu
 
 usage(){
-  echo "Usage: ${0##*/} QUBE" >&2
+  printf '%s\n' "Usage: ${0##*/} QUBE" >&2
   exit "${1:-1}"
 }
 
@@ -24,49 +24,49 @@ case "${1-}" in
 esac
 
 mgmt="$(qubes-prefs management_dispvm)"
-echo "GLOBAL"
-echo "management_dispvm: ${mgmt}"
+printf '%s\n' "GLOBAL"
+printf '%s\n' "management_dispvm: ${mgmt}"
 tpl_mgmt="$(qvm-prefs "${mgmt}" template)"
-echo "management_dispvm template: ${tpl_mgmt}"
-echo "management_dispvm template features:"
+printf '%s\n' "management_dispvm template: ${tpl_mgmt}"
+printf '%s\n' "management_dispvm template features:"
 get_qube_feat "${tpl_mgmt}"
 
 if ! qvm-check -q -- "${wanted_qube}"; then
-  echo "error: qube '${wanted_qube}' does not exist" >&2
+  printf '%s\n' "error: qube '${wanted_qube}' does not exist" >&2
   exit 1
 fi
-echo ""
-echo "WANTED"
-echo "qube: ${wanted_qube}"
+printf '%s\n' ""
+printf '%s\n' "WANTED"
+printf '%s\n' "qube: ${wanted_qube}"
 class="$(qvm-prefs "${wanted_qube}" klass)"
-echo "class: ${class}"
+printf '%s\n' "class: ${class}"
 case "${class}" in
   AppVM)
     tpl_wanted_qube="$(qvm-prefs "${wanted_qube}" template)"
-    echo "template: ${tpl_wanted_qube}"
-    echo "template features:"
+    printf '%s\n' "template: ${tpl_wanted_qube}"
+    printf '%s\n' "template features:"
     get_qube_feat "${tpl_wanted_qube}"
     ;;
   DispVM)
     dvm_wanted_qube="$(qvm-prefs "${wanted_qube}" template)"
-    echo "disposable template: ${dvm_wanted_qube}"
+    printf '%s\n' "disposable template: ${dvm_wanted_qube}"
     tpl_wanted_qube="$(qvm-prefs "${dvm_wanted_qube}" template)"
-    echo "template: ${tpl_wanted_qube}"
-    echo "template features:"
+    printf '%s\n' "template: ${tpl_wanted_qube}"
+    printf '%s\n' "template features:"
     get_qube_feat "${tpl_wanted_qube}"
     ;;
   AdminVM) ;;
   StandaloneVM|TemplateVM)
     get_qube_feat "${wanted_qube}"
     ;;
-  *) echo "Unsupported qube class" >&2; exit 1;;
+  *) printf '%s\n' "Unsupported qube class" >&2; exit 1;;
 esac
 wanted_mgmt="$(qvm-prefs "${wanted_qube}" management_dispvm)"
-echo "${wanted_qube} management_dispvm: ${wanted_mgmt}"
+printf '%s\n' "${wanted_qube} management_dispvm: ${wanted_mgmt}"
 if test "${wanted_mgmt}" = "${mgmt}"; then
   exit
 fi
 wanted_tpl_mgmt="$(qvm-prefs "${wanted_mgmt}" template)"
-echo "${wanted_qube} management_dispvm template: ${wanted_tpl_mgmt}"
-echo "${wanted_qube} management_dispvm template features:"
+printf '%s\n' "${wanted_qube} management_dispvm template: ${wanted_tpl_mgmt}"
+printf '%s\n' "${wanted_qube} management_dispvm template features:"
 get_qube_feat "${wanted_tpl_mgmt}"
diff --git a/salt/dom0/files/bin/qvm-port-forward b/salt/dom0/files/bin/qvm-port-forward
--- a/salt/dom0/files/bin/qvm-port-forward
+++ b/salt/dom0/files/bin/qvm-port-forward
@@ -29,7 +29,7 @@ validate_handle(){
   untrusted_handle="${2}"
   case "${untrusted_handle}" in
     ""|*[!0-9]*)
-      echo "error: ${qube}: invalid handle" >&2
+      printf '%s\n' "error: ${qube}: invalid handle" >&2
       exit 1
       ;;
     *) ;;
@@ -41,7 +41,7 @@ validate_ipv4(){
   untrusted_ip="${2}"
   case "${untrusted_ip}" in
     ""|*[!0-9./]*)
-      echo "error: ${qube}: invalid IPv4 address" >&2
+      printf '%s\n' "error: ${qube}: invalid IPv4 address" >&2
       exit 1
       ;;
     *) ;;
@@ -53,7 +53,7 @@ validate_ipv6(){
   untrusted_ip="${2}"
   case "${untrusted_ip}" in
     ""|*[!0-9a-f:/]*)
-      echo "error: ${qube}: invalid IPv6 address" >&2
+      printf '%s\n' "error: ${qube}: invalid IPv6 address" >&2
       exit 1
       ;;
     *) ;;
@@ -65,7 +65,7 @@ validate_dev(){
   untrusted_dev="${2}"
   case "${untrusted_dev}" in
     ""|*[!0-9A-Za-z]*)
-      echo "error: ${qube}: invalid device name" >&2
+      printf '%s\n' "error: ${qube}: invalid device name" >&2
       exit 1
       ;;
     *) ;;
@@ -123,7 +123,7 @@ forward() {
   from_ip="${untrusted_from_ip}"
 
   to_ip="$(qvm-prefs --get -- "${to_qube}" ip)"
-  to_ip_escaped="$(echo "${to_ip}" | tr "." "-")"
+  to_ip_escaped="$(printf '%s\n' "${to_ip}" | tr "." "-")"
   hook="${hook_prefix}${to_ip}-${proto}-${port}.sh"
 
   if test "${from_ip}" = "None"; then
@@ -147,11 +147,11 @@ add rule ip qubes ${forward_chain} ${forward_rule}'"
   delete_rule "${from_qube}" "${forward_chain}" "${forward_rule}"
   delete_rule "${from_qube}" "${dnat_chain}" "${dnat_rule}"
   if test "${action}" = "del"; then
-    echo "info: ${from_qube}: deleting rules" >&2
+    printf '%s\n' "info: ${from_qube}: deleting rules" >&2
     run_qube "${from_qube}" "rm -f ${hook}"
   else
     msg="adding forward rule dev ${dev} saddr ${lan_ip} daddr ${to_ip}"
-    echo "info: ${from_qube}: ${msg}" >&2
+    printf '%s\n' "info: ${from_qube}: ${msg}" >&2
     run_qube "${from_qube}" "${full_rule}"
 
     if test "${persistent}" = "1"; then
@@ -187,7 +187,7 @@ ${full_rule}"
 
       create_net_dir "${from_qube}"
       run_qube "${from_qube}" \
-        "echo \"${full_rule}\" | tee -- \"${hook}\" >/dev/null"
+        "printf '%s\n' \"${full_rule}\" | tee -- \"${hook}\" >/dev/null"
       run_qube "${from_qube}" "chmod -- +x ${hook}"
     fi
   fi
@@ -205,10 +205,10 @@ input() {
 
   delete_rule "${qube}" "custom-input" "${custom_input_rule}"
   if test "${action}" = "del"; then
-    echo "info: ${qube}: deleting rules" >&2
+    printf '%s\n' "info: ${qube}: deleting rules" >&2
     run_qube "${qube}" "rm -f ${hook}"
   else
-    echo "info: ${qube}: adding input rule daddr ${to_ip}" >&2
+    printf '%s\n' "info: ${qube}: adding input rule daddr ${to_ip}" >&2
     run_qube "${qube}" "${input_rule}"
     if test "${persistent}" = "1"; then
       input_rule="#!/bin/sh
@@ -230,7 +230,7 @@ fi
 ${input_rule}"
 
       run_qube "${qube}" \
-        "echo \"${input_rule}\" | tee -- \"${hook}\" >/dev/null"
+        "printf '%s\n' \"${input_rule}\" | tee -- \"${hook}\" >/dev/null"
       run_qube "${qube}" "chmod -- +x ${hook}"
     fi
   fi
@@ -247,7 +247,7 @@ get_lan(){
   dev="${untrusted_dev}"
 
   if test -z "${dev}"; then
-    echo "error: ${qube}: could not find any device that is up" >&2
+    printf '%s\n' "error: ${qube}: could not find any device that is up" >&2
     exit 1
   fi
 
@@ -258,7 +258,7 @@ get_lan(){
   lan_ip="${untrusted_lan_ip}"
 
   if test -z "${lan_ip}"; then
-    echo "error: ${qube}: could not find LAN from device ${dev}" >&2
+    printf '%s\n' "error: ${qube}: could not find LAN from device ${dev}" >&2
     exit 1
   fi
 }
@@ -266,8 +266,9 @@ get_lan(){
 test_qvm_run(){
   qube="${1}"
   # shellcheck disable=SC2310
-  if ! run_qube "${qube}" echo "Test QUBESRPC" >/dev/null 2>&1; then
-    echo "error: ${qube}: RPC qubes.VMShell failed, use a different qube" >&2
+  if ! run_qube "${qube}" printf '%s\n' "Test QUBESRPC" >/dev/null 2>&1; then
+    err_msg="error: ${qube}: RPC qubes.VMShell failed, use a different qube"
+    printf '%s\n' "${err_msg}" >&2
     exit 1
   fi
 }
@@ -280,19 +281,23 @@ recurse_netvms() {
     case "${cmd}" in
       show-upstream) test_qvm_run "${rec_qube}";;
       apply-rules) forward "${rec_netvm}" "${rec_qube}";;
-      *) echo "Unsupported command passed to recurse_netvms()" >&2; exit 1;;
+      *) printf '%s\n' "Unsupported command passed to recurse_netvms()" >&2
+        exit 1
+        ;;
     esac
     recurse_netvms "${cmd}" "${rec_netvm}"
   fi
   case "${cmd}" in
     show-upstream) get_lan "${rec_qube}";;
     apply-rules) ;;
-    *) echo "Unsupported command passed to recurse_netvms()" >&2; exit 1;;
+    *) printf '%s\n' "Unsupported command passed to recurse_netvms()" >&2
+      exit 1
+      ;;
   esac
 }
 
 usage() {
-  echo "Usage: ${0##*/} OPTIONS
+  printf '%s\n' "Usage: ${0##*/} OPTIONS
 Option syntax:
   --action ACTION --qube QUBE --port PORT --proto PROTO [--persistent]
 Options:
@@ -314,33 +319,42 @@ Warn: Persistent rules of disposable netvm are saved to its template" >&2
 check_opt(){
   case "${action:-}" in
     add|del);;
-    *) echo "error: action must be either 'add' or 'del'" >&2; exit 1;;
+    *)
+      printf '%s\n' "error: action must be either 'add' or 'del'" >&2
+      exit 1
+      ;;
   esac
 
   case "${proto:-}" in
     tcp|udp);;
-    *) echo "error: protocol must be only 'tcp' or 'udp'" >&2; exit 1;;
+    *)
+      printf '%s\n' "error: protocol must be only 'tcp' or 'udp'" >&2
+      exit 1
+      ;;
   esac
 
   case "${port:-}" in
-    ""|*[!0-9]*) echo "error: port must be only numbers" >&2; exit 1;;
+    ""|*[!0-9]*)
+      printf '%s\n' "error: port must be only numbers" >&2
+      exit 1
+      ;;
     *)
   esac
 
   if test "${port}" -ge 1 && test "${port}" -le 65535; then
     true
   else
-    echo "error: port must be in range 1-65535" >&2
+    printf '%s\n' "error: port must be in range 1-65535" >&2
     exit 1
   fi
 
   if test -z "${target_qube:-}"; then
-    echo "error: qube name not provided" >&2
+    printf '%s\n' "error: qube name not provided" >&2
     exit 1
   fi
 
   if ! qvm-check -- "${target_qube}" >/dev/null 2>&1; then
-    echo "error: qube '${target_qube}' not found." >&2
+    printf '%s\n' "error: qube '${target_qube}' not found." >&2
     exit 1
   fi
 }
@@ -352,7 +366,7 @@ persistent=""
 if ! OPTS=$(getopt -o h,a:q:p:n:s \
   --long help,action:,qube:,port:,proto:,persistent -n "${0}" -- "${@}")
 then
-  echo "An error occurred while parsing options." >&2
+  printf '%s\n' "An error occurred while parsing options." >&2
   exit 1
 fi
 
@@ -369,7 +383,7 @@ while test "${#}" -gt "0"; do
     -s|--persistent) persistent=1; shift;;
     -h|--help) usage;;
     --) break;;
-    *) echo "Unsupported option" >&2; exit 1;;
+    *) printf '%s\n' "Unsupported option" >&2; exit 1;;
   esac
   shift
 done
diff --git a/salt/dom0/files/bin/qvm-screenshot b/salt/dom0/files/bin/qvm-screenshot
--- a/salt/dom0/files/bin/qvm-screenshot
+++ b/salt/dom0/files/bin/qvm-screenshot
@@ -20,37 +20,37 @@ take_screenshot() {
       case "${screenshot_type}" in
         window) spectacle -a -o "${screenshot_file}";;
         fullscreen) spectacle -f -o "${screenshot_file}";;
-        *) echo "Unsupported screenshot type" >&2; exit 1;;
+        *) printf '%s\n' "Unsupported screenshot type" >&2; exit 1;;
       esac
       ;;
     xfce4-screenshooter)
       case "${screenshot_type}" in
         window) xfce4-screenshooter -w -s "${screenshot_file}";;
         fullscreen) xfce4-screenshooter -f -s "${screenshot_file}";;
-        *) echo "Unsupported screenshot type" >&2; exit 1;;
+        *) printf '%s\n' "Unsupported screenshot type" >&2; exit 1;;
       esac
       ;;
     scrot)
       case "${screenshot_type}" in
         window) scrot -s -b "${screenshot_file}";;
         fullscreen) scrot -b "${screenshot_file}";;
-        *) echo "Unsupported screenshot type" >&2; exit 1;;
+        *) printf '%s\n' "Unsupported screenshot type" >&2; exit 1;;
       esac
       ;;
     maim)
       case "${screenshot_type}" in
         window) maim -s -o -u "${screenshot_file}";;
         fullscreen) maim -o -u "${screenshot_file}";;
-        *) echo "Unsupported screenshot type" >&2; exit 1;;
+        *) printf '%s\n' "Unsupported screenshot type" >&2; exit 1;;
       esac
       ;;
-    *) echo "Unsupported screenshot tool" >&2; exit 1;;
+    *) printf '%s\n' "Unsupported screenshot tool" >&2; exit 1;;
   esac
 }
 
 print_help(){
   # editorconfig-checker-disable
-  echo "Usage: ${0##*/} [OPTIONS]
+  printf '%s\n' "Usage: ${0##*/} [OPTIONS]
  -h, --help                  print this help message and exit
 Capture mode:
  -r, --region                select only a region of the screen
@@ -121,7 +121,7 @@ while test "$#" -gt 0; do
       dialog_cmd_wanted="${1}"
       ;;
     *)
-      echo "Unknown option: ${key}"
+      printf '%s\n' "Unknown option: ${key}"
       exit 1
     ;;
   esac
@@ -131,14 +131,14 @@ done
 if test -n "${dialog_cmd_wanted}"; then
   if ! command -v "${dialog_cmd_wanted}" >/dev/null; then
     msg="wanted dialog program not found: ${dialog_cmd_wanted}"
-    echo "[ERROR] ${msg}"
+    printf '%s\n' "[ERROR] ${msg}"
     exit 1
   fi
   case "${dialog_cmd_wanted}" in
     kdialog|zenity);;
     *)
       msg="wanted dialog program unsupported: ${dialog_cmd_wanted}"
-      echo "[ERROR] ${msg}"
+      printf '%s\n' "[ERROR] ${msg}"
       exit 1
       ;;
   esac
@@ -150,7 +150,7 @@ else
     dialog_cmd="zenity"
   fi
   if test -z "${dialog_cmd}"; then
-    echo "[ERROR] dialog programs not found: zenity kdialog"
+    printf '%s\n' "[ERROR] dialog programs not found: zenity kdialog"
     exit 1
   fi
 fi
@@ -158,11 +158,11 @@ fi
 if test -n "${screenshot_cmd_wanted}"; then
   if ! command -v "${screenshot_cmd_wanted}" >/dev/null; then
     msg="wanted screenshot program not found: ${screenshot_cmd_wanted}"
-    echo "[ERROR] ${msg}"
+    printf '%s\n' "[ERROR] ${msg}"
     case "${dialog_cmd}" in
       zenity) zenity --info --text "${msg}";;
       kdialog) kdialog --msgbox "${msg}";;
-      *) echo "Unsupported dialog command" >&2; exit 1;;
+      *) printf '%s\n' "Unsupported dialog command" >&2; exit 1;;
     esac
     exit 1
   fi
@@ -170,7 +170,7 @@ if test -n "${screenshot_cmd_wanted}"; then
     maim|scrot|spectacle|xfce4-screenshooter);;
     *)
       msg="wanted screenshot program unsupported: ${screenshot_cmd_wanted}"
-      echo "[ERROR] ${msg}"
+      printf '%s\n' "[ERROR] ${msg}"
       exit 1
       ;;
   esac
@@ -188,11 +188,11 @@ else
   if test -z "${screenshot_cmd}"; then
     msg="screenshot programs not found"
     msg="${msg}: spectacle xfce4-screenshooter scrot maim"
-    echo "[ERROR] ${msg}"
+    printf '%s\n' "[ERROR] ${msg}"
     case "${dialog_cmd}" in
       zenity) zenity --info --text "${msg}";;
       kdialog) kdialog --msgbox "${msg}";;
-      *) echo "Unsupported dialog command" >&2; exit 1;;
+      *) printf '%s\n' "Unsupported dialog command" >&2; exit 1;;
     esac
     exit 1
   fi
@@ -217,23 +217,23 @@ if test -z "${screenshot_type_text}"; then
         "Fullscreen" "Fullscreen" off \
       )"
       ;;
-    *) echo "Unsupported dialog command" >&2; exit 1;;
+    *) printf '%s\n' "Unsupported dialog command" >&2; exit 1;;
   esac
 fi
 
 case "${screenshot_type_text}" in
   "Region or Window") take_screenshot window;;
   "Fullscreen") take_screenshot fullscreen;;
-  *) echo "[ERROR] mode not selected"; exit 1;;
+  *) printf '%s\n' "[ERROR] mode not selected"; exit 1;;
 esac
 
 if ! test -f "${screenshot_file}"; then
   msg="Screenshot was not saved in GuiVM"
-  echo "[ERROR] ${msg}"
+  printf '%s\n' "[ERROR] ${msg}"
   case "${dialog_cmd}" in
     zenity) zenity --warning --text "${msg}";;
     kdialog) kdialog --sorry "${msg}";;
-    *) echo "Unsupported dialog command" >&2; exit 1;;
+    *) printf '%s\n' "Unsupported dialog command" >&2; exit 1;;
   esac
   exit 1
 fi
@@ -259,7 +259,7 @@ if test "${screenshot_action_supplied}" != "1"; then
         "Move file" "Move file" off
       )"
       ;;
-    *) echo "Unsupported dialog command" >&2; exit 1;;
+    *) printf '%s\n' "Unsupported dialog command" >&2; exit 1;;
   esac
 
   if test -z "${screenshot_action_text}"; then
@@ -268,7 +268,8 @@ if test "${screenshot_action_supplied}" != "1"; then
 
   IFSOLD="${IFS}"
   IFS="|"
-  screenshot_action_text="$(echo "${screenshot_action_text}" | tr "\n" "|")"
+  screenshot_action_text="$(printf '%s\n' "${screenshot_action_text}" | \
+    tr "\n" "|")"
   for val in ${screenshot_action_text}; do
     case "${val}" in
       "Exit") exit_required=1;;
@@ -292,26 +293,27 @@ if test -z "${qube}"; then
   dialog_title="Select destination qube (Unix based):"
   case "${dialog_cmd}" in
     zenity)
-      qube_list="$(echo "${qube_list}" | sed -e "s/^/FALSE /")"
+      qube_list="$(printf '%s\n' "${qube_list}" | sed -e "s/^/FALSE /")"
       # shellcheck disable=SC2086
       qube="$(zenity --list  --width=200 --height=390 \
               --text "${dialog_title}" \
               --radiolist --column "Pick" --column "qube" ${qube_list})"
       ;;
     kdialog)
-      qube_list="$(echo "${qube_list}" | sed -e "s/\(.*\)/\1 \1 off/")"
+      qube_list="$(printf '%s\n' "${qube_list}" | \
+        sed -e "s/\(.*\)/\1 \1 off/")"
       # shellcheck disable=SC2086
       qube="$(kdialog --radiolist "${dialog_title}" ${qube_list})"
       ;;
-    *) echo "Unsupported dialog command" >&2; exit 1;;
+    *) printf '%s\n' "Unsupported dialog command" >&2; exit 1;;
   esac
   if test -z "${qube}"; then
     msg="qube was not selected"
-    echo "[ERROR] ${msg}"
+    printf '%s\n' "[ERROR] ${msg}"
     case "${dialog_cmd}" in
       zenity) zenity --error --text "${msg}";;
       kdialog) kdialog --error "${msg}";;
-      *) echo "Unsupported dialog command" >&2; exit 1;;
+      *) printf '%s\n' "Unsupported dialog command" >&2; exit 1;;
     esac
     exit 1
   fi
@@ -319,11 +321,11 @@ fi
 
 if ! qvm-check -- "${qube}" >/dev/null 2>&1; then
   msg="qube doesn't exist: ${qube}"
-  echo "[ERROR] ${msg}"
+  printf '%s\n' "[ERROR] ${msg}"
   case "${dialog_cmd}" in
     zenity) zenity --error --text "${msg}";;
     kdialog) kdialog --error "${msg}";;
-    *) echo "Unsupported dialog command" >&2; exit 1;;
+    *) printf '%s\n' "Unsupported dialog command" >&2; exit 1;;
   esac
   exit 1
 fi
diff --git a/salt/mail/files/reader/bin/qusal-send-mail b/salt/mail/files/reader/bin/qusal-send-mail
--- a/salt/mail/files/reader/bin/qusal-send-mail
+++ b/salt/mail/files/reader/bin/qusal-send-mail
@@ -10,7 +10,7 @@ set -eu
 
 MSMTP_Q="${MSMTP_Q:-"${Q:-"${HOME}/.msmtp.queue"}"}"
 if test -z "${MSMTP_Q}" || test ! -d "${MSMTP_Q}"; then
-  echo "Queue dir '${MSMTP_Q}' not found" >&2
+  printf '%s\n' "Queue dir '${MSMTP_Q}' not found" >&2
   exit 1
 fi
 
@@ -18,11 +18,11 @@ cd "${MSMTP_Q}" || exit 1
 
 for mail in *; do
   if ! test -e "${mail}"; then
-    echo "Mail queue '${MSMTP_Q}' is empty" >&2
+    printf '%s\n' "Mail queue '${MSMTP_Q}' is empty" >&2
     exit 1
   fi
   if ! test -f "${mail}"; then
-    echo "Mail '${mail}' is not a regular file" >&2
+    printf '%s\n' "Mail '${mail}' is not a regular file" >&2
     exit 1
   fi
 done
diff --git a/salt/sys-bitcoin/files/client/bin/bitcoin-rpcauth-save b/salt/sys-bitcoin/files/client/bin/bitcoin-rpcauth-save
--- a/salt/sys-bitcoin/files/client/bin/bitcoin-rpcauth-save
+++ b/salt/sys-bitcoin/files/client/bin/bitcoin-rpcauth-save
@@ -12,8 +12,8 @@ auth="$(qrexec-client-vm -tT -- @default qusal.BitcoinAuthGet)"
 
 if test -n "${auth}"; then
   mkdir -p -- ~/.bitcoin/.cookie
-  echo "${auth}" | tee -- ~/.bitcoin/.cookie >/dev/null
+  printf '%s\n' "${auth}" | tee -- ~/.bitcoin/.cookie >/dev/null
 else
-  echo "failed to get Bitcoin Authentication" >&2
+  printf '%s\n' "failed to get Bitcoin Authentication" >&2
   exit 1
 fi
diff --git a/salt/sys-bitcoin/files/server/bin/bitcoin-rpcwhitelist-cookie b/salt/sys-bitcoin/files/server/bin/bitcoin-rpcwhitelist-cookie
--- a/salt/sys-bitcoin/files/server/bin/bitcoin-rpcwhitelist-cookie
+++ b/salt/sys-bitcoin/files/server/bin/bitcoin-rpcwhitelist-cookie
@@ -8,11 +8,12 @@ set -eu
 conf="${HOME}/.bitcoin/conf.d/cookie.conf"
 
 if ! systemctl is-active bitcoind >/dev/null 2>&1; then
-  echo "systemd service 'bitcoind' is inactive" >&2
-  echo "remote RPC can't add crendetials" >&2
+  printf '%s\n' "systemd service 'bitcoind' is inactive" >&2
+  printf '%s\n' "remote RPC can't add crendetials" >&2
   exit 1
 fi
 
 rpc_list="$(bitcoin-cli help | awk '/^[a-z]/{print $1}' | tr "\n" ",")"
 
-echo "rpcwhitelist=__cookie__:${rpc_list}" | tee -- "${conf}" >/dev/null
+printf '%s\n' "rpcwhitelist=__cookie__:${rpc_list}" | \
+  tee -- "${conf}" >/dev/null
diff --git a/salt/sys-bitcoin/files/server/bin/bitcoin-whitepaper b/salt/sys-bitcoin/files/server/bin/bitcoin-whitepaper
--- a/salt/sys-bitcoin/files/server/bin/bitcoin-whitepaper
+++ b/salt/sys-bitcoin/files/server/bin/bitcoin-whitepaper
@@ -22,7 +22,7 @@ check_installed(){
   for prog in "${@}"; do
     # shellcheck disable=SC2310
     if ! has "${prog}"; then
-      echo "Missing program: ${prog}" >&2
+      printf '%s\n' "Missing program: ${prog}" >&2
       missing_programs=1
     fi
   done
@@ -33,11 +33,11 @@ check_installed(){
 
 validate_dir(){
   if ! test -d "${dir}"; then
-    echo "Directory '${dir}' does not exist" >&2
+    printf '%s\n' "Directory '${dir}' does not exist" >&2
     exit 1
   fi
   if ! test -w "${dir}"; then
-    echo "Directory '${dir}' is not writable" >&2
+    printf '%s\n' "Directory '${dir}' is not writable" >&2
     exit 1
   fi
 }
@@ -84,9 +84,9 @@ gettxout(){
 }
 
 usage(){
-  echo "Usage: ${0##*/} getblock|getrawtransaction|gettxout [DIR]"
-  echo "Note: gettxout works with pruned node"
-  echo "Note: DIR defaults to \${HOME}"
+  printf '%s\n' "Usage: ${0##*/} getblock|getrawtransaction|gettxout [DIR]"
+  printf '%s\n' "Note: gettxout works with pruned node"
+  printf '%s\n' "Note: DIR defaults to \${HOME}"
   exit 1
 }
 
diff --git a/salt/sys-cacher/files/client/bin/apt-cacher-ng-repo b/salt/sys-cacher/files/client/bin/apt-cacher-ng-repo
--- a/salt/sys-cacher/files/client/bin/apt-cacher-ng-repo
+++ b/salt/sys-cacher/files/client/bin/apt-cacher-ng-repo
@@ -33,17 +33,17 @@ set_proxy_marker(){
       msg="found marker ${marker_end_text} but not ${marker_begin_text}"
       msg="${msg} in ${proxy_file}."
       msg="${msg} fix it by removing markers or adding missing ones and retry"
-      echo "Error: ${msg}" >&2
+      printf '%s\n' "Error: ${msg}" >&2
       exit 1
     fi
     cp -- "${proxy_file}" "${proxy_file}.qubes-orig"
-    echo "${marker_begin}" | tee -a -- "${proxy_file}" >/dev/null
-    echo "${marker_end}" | tee -a -- "${proxy_file}" >/dev/null
+    printf '%s\n' "${marker_begin}" | tee -a -- "${proxy_file}" >/dev/null
+    printf '%s\n' "${marker_end}" | tee -a -- "${proxy_file}" >/dev/null
   elif ! grep -q -e "^${marker_end}$" -- "${proxy_file}"; then
     msg="found marker ${marker_begin_text} but not ${marker_end_text}"
     msg="${msg} in ${proxy_file}."
     msg="${msg} fix it by removing markers or adding missing ones and retry"
-    echo "error: ${msg}" >&2
+    printf '%s\n' "error: ${msg}" >&2
     exit 1
   fi
 
@@ -80,7 +80,8 @@ check_netvm_cacher(){
   if test -f /var/run/qubes-service/netvm-cacher; then
     proxy_host="$(qubesdb-read /qubes-gateway)"
     if test -z "${proxy_host}"; then
-      echo "Error: service netvm-cacher enabled but netvm IP not found" >&2
+      printf '%s\n' \
+        "Error: service netvm-cacher enabled but netvm IP not found" >&2
       return 1
     fi
   fi
@@ -90,7 +91,8 @@ check_netvm_cacher(){
 }
 
 reject_os(){
-  echo "${0##*/} does not support your Operating System distribution." >&2
+  msg_unsupported="${0##*/} does not support your OS distribution."
+  printf '%s\n' "${msg_unsupported}" >&2
   exit 1
 }
 
@@ -183,7 +185,7 @@ EOF
           -e "s|^\s*#.*metalink\s*=|metalink=|w ${changes_file}" \
         -- {} \+ 2>/dev/null || true
         ;;
-      *) echo "Unsupported action" >&2; exit 1
+      *) printf '%s\n' "Unsupported action" >&2; exit 1
     esac
 
   elif test -e /etc/debian_version && test ! -e /usr/share/whonix/marker; then
@@ -236,7 +238,7 @@ EOF
           -e "${list_expr}" -e "${sources_expr}" \
         -- {} \+
         ;;
-      *) echo "Unsupported action" >&2; exit 1
+      *) printf '%s\n' "Unsupported action" >&2; exit 1
     esac
 
   elif test -e /etc/arch-release; then
@@ -289,7 +291,7 @@ EOF
           -e "${repo_regex}" \
         -- {} \+
         ;;
-      *) echo "Unsupported action" >&2; exit 1
+      *) printf '%s\n' "Unsupported action" >&2; exit 1
     esac
 
   else
@@ -306,8 +308,8 @@ set_proxy_unspecific_os(){
 }
 
 usage(){
-  echo "Usage: ${0##*/} [install|uninstall]"
-  echo "Note: autodetection occurs if not argument is specified"
+  printf '%s\n' "Usage: ${0##*/} [install|uninstall]"
+  printf '%s\n' "Note: autodetection occurs if not argument is specified"
   exit 1
 }
 
@@ -330,7 +332,7 @@ esac
 
 uid="$(id -u)"
 if test "${uid}" != "0"; then
-  echo "Error: Permission denied, action requires root privileges."
+  printf '%s\n' "Error: Permission denied, action requires root privileges."
   exit 1
 fi
 
@@ -339,10 +341,10 @@ set_proxy_os
 set_proxy_unspecific_os
 
 ## Stateful Salt cmd Module.
-echo
+printf '\n'
 if test -s "${changes_file}"; then
-  echo "changed=yes comment='configuration was modified'"
+  printf '%s\n' "changed=yes comment='configuration was modified'"
 else
-  echo "changed=no comment='configuration remained untouched'"
+  printf '%s\n' "changed=no comment='configuration remained untouched'"
 fi
 exit
diff --git a/salt/sys-electrumx/files/server/bin/electrumx-cookie-save b/salt/sys-electrumx/files/server/bin/electrumx-cookie-save
--- a/salt/sys-electrumx/files/server/bin/electrumx-cookie-save
+++ b/salt/sys-electrumx/files/server/bin/electrumx-cookie-save
@@ -9,16 +9,16 @@ electrumx_conf="${HOME}/.electrumx/conf.d/cookie.conf"
 cookie="${HOME}/.bitcoin/.cookie"
 
 if ! test -f "${cookie}"; then
-  echo "cookie not found" >&2
+  printf '%s\n' "cookie not found" >&2
   exit 1
 fi
 
 if ! test -r "${cookie}"; then
-  echo "cannot read from cookie" >&2
+  printf '%s\n' "cannot read from cookie" >&2
   exit 1
 fi
 
 auth="$(cat -- "${cookie}")"
 
-echo "DAEMON_URL=${auth}@127.0.0.1:8332" | \
+printf '%s\n' "DAEMON_URL=${auth}@127.0.0.1:8332" | \
   tee -- "${electrumx_conf}" >/dev/null
diff --git a/salt/sys-git/files/client/git-core/git-init-qrexec b/salt/sys-git/files/client/git-core/git-init-qrexec
--- a/salt/sys-git/files/client/git-core/git-init-qrexec
+++ b/salt/sys-git/files/client/git-core/git-init-qrexec
@@ -12,16 +12,16 @@ case "${GIT_TRACE_HELPER:-}" in
 esac
 
 usage(){
-  echo "Usage: ${helper} [<qube>] [<repository>]" >&2
-  echo "Note: qube defaults to @default" >&2
-  echo "Note: repository defaults to current working repository" >&2
+  printf '%s\n' "Usage: ${helper} [<qube>] [<repository>]" >&2
+  printf '%s\n' "Note: qube defaults to @default" >&2
+  printf '%s\n' "Note: repository defaults to current working repository" >&2
   exit 1
 }
 
 is_git_repo(){
   if ! git rev-parse --show-toplevel >/dev/null 2>&1; then
-    echo "Error: Current working directory is not in a git repository" >&2
-    echo "Error: Run from a repository or pass the name as an argument" >&2
+    printf '%s\n' "Error: CWD is not a git repository" >&2
+    printf '%s\n' "Error: Run from a repository or provide its name" >&2
     usage
   fi
 }
diff --git a/salt/sys-git/files/client/git-core/git-remote-qrexec b/salt/sys-git/files/client/git-core/git-remote-qrexec
--- a/salt/sys-git/files/client/git-core/git-remote-qrexec
+++ b/salt/sys-git/files/client/git-core/git-remote-qrexec
@@ -14,18 +14,18 @@ set -eu
 usage(){
   url_format="${scheme}://<authority>/<path>"
   url_format="${url_format}[?query=value][&other_query=value]"
-  echo "Usage: ${helper} <remote> [${url_format}]" >&2
+  printf '%s\n' "Usage: ${helper} <remote> [${url_format}]" >&2
 }
 
 die(){
   usage
-  echo "Error: ${1}" >&2
+  printf '%s\n' "Error: ${1}" >&2
   exit 1
 }
 
 log(){
   case "${GIT_TRACE_REMOTE_HELPER:-}" in
-    true|1) echo "${@}" >&2;;
+    true|1) printf '%s\n' "${@}" >&2;;
     *) ;;
   esac
 }
@@ -34,7 +34,7 @@ log(){
 validate_url(){
   url_valid=""
   url_check="${1?}"
-  scheme_user_url="$(echo "${url_check}" | sed -e "s|://.*||")"
+  scheme_user_url="$(printf '%s\n' "${url_check}" | sed -e "s|://.*||")"
 
   ## Scheme must be the same as the one in the name of this script.
   ## Checks if Authority and Path exist, but not if they are valid, this is
@@ -48,24 +48,25 @@ validate_url(){
   esac
 
   urn_pattern="[0-9A-Za-z@:_.-]+/[0-9A-Za-z_.-]+(\?[0-9A-Za-z=&_-]*)?"
-  if ! (echo "${url_valid}" | grep -qE -e "^${scheme}://${urn_pattern}$")
+  if ! (printf '%s\n' "${url_valid}" | \
+    grep -qE -e "^${scheme}://${urn_pattern}$")
   then
     die "URL contains forbidden characters"
   fi
 
-  echo "${url_valid}"
+  printf '%s\n' "${url_valid}"
 }
 
 get_urn(){
-  echo "${1#*://}"
+  printf '%s\n' "${1#*://}"
 }
 
 get_authority(){
-  echo "${1%%/*}"
+  printf '%s\n' "${1%%/*}"
 }
 
 get_path(){
-  echo "${1##*/}" | cut -d "?" -f1
+  printf '%s\n' "${1##*/}" | cut -d "?" -f1
 }
 
 get_query(){
@@ -74,7 +75,7 @@ get_query(){
   if test "${1}" != "${1##*\?}"; then
     query="${1##*\?}"
   fi
-  echo "${query}"
+  printf '%s\n' "${query}"
 }
 
 ## Find remote-<scheme>-<command>.
@@ -99,7 +100,7 @@ send_cap(){
   cap="${1}"
   shift
 
-  if ! (echo "${capabilities}" | grep -q -e "^${cap}$"); then
+  if ! (printf '%s\n' "${capabilities}" | grep -q -e "^${cap}$"); then
     die "Unsupported capability: '${cap}'"
   fi
 
diff --git a/salt/sys-git/files/client/git-core/git-remote-qrexec-connect b/salt/sys-git/files/client/git-core/git-remote-qrexec-connect
--- a/salt/sys-git/files/client/git-core/git-remote-qrexec-connect
+++ b/salt/sys-git/files/client/git-core/git-remote-qrexec-connect
@@ -7,19 +7,19 @@
 set -eu
 
 usage(){
-  echo "Usage: ${helper} (git-upload-pack|git-receive-pack)"
-  echo "Note: ${helper} is supposed to be called by ${parent_helper}"
+  printf '%s\n' "Usage: ${helper} (git-upload-pack|git-receive-pack)"
+  printf '%s\n' "Note: ${helper} is supposed to be called by ${parent_helper}"
   exit 1
 }
 
 die(){
-  echo "Error: ${1}" >&2
+  printf '%s\n' "Error: ${1}" >&2
   exit 1
 }
 
 log(){
   case "${GIT_TRACE_REMOTE_HELPER:-}" in
-    true|1) echo "${@}" >&2;;
+    true|1) printf '%s\n' "${@}" >&2;;
     *) ;;
   esac
 }
@@ -61,7 +61,7 @@ vendor="qusal"
 default_qube="sys-git"
 rpc_cmd="${vendor}.${rpc}+${path}"
 
-if echo "${query}" | \
+if printf '%s\n' "${query}" | \
   grep -qE -e "(^|&)verify_signatures=(1|[tT]rue|yes|on)($|&)"
 then
   die "Remote helper does not support signature verification yet"
diff --git a/salt/sys-ssh-agent/files/server/bin/qvm-ssh-agent b/salt/sys-ssh-agent/files/server/bin/qvm-ssh-agent
--- a/salt/sys-ssh-agent/files/server/bin/qvm-ssh-agent
+++ b/salt/sys-ssh-agent/files/server/bin/qvm-ssh-agent
@@ -9,7 +9,7 @@ set -eu
 service="qusal-ssh-agent"
 
 usage(){
-  echo "Usage: ${0##*/} [ls|add] <AGENT>
+  printf '%s\n' "Usage: ${0##*/} [ls|add] <AGENT>
   ls: list agent(s)
   add: add keys to agent(s)
   reload: reload/re-add keys from agent(s)
@@ -23,8 +23,8 @@ Example:
 ls_agent(){
   socket="/tmp/${service}/${agent}.sock"
   test -S "${socket}" || return 1
-  agent="$(echo "${socket}" | sed -e "s|.*${service}/||;s/\.sock//")"
-  echo "Agent: (${agent}) ${socket}"
+  agent="$(printf '%s\n' "${socket}" | sed -e "s|.*${service}/||;s/\.sock//")"
+  printf '%s\n' "Agent: (${agent}) ${socket}"
   SSH_AUTH_SOCK="${socket}" ssh-add -l || true
 }
 
@@ -33,7 +33,7 @@ add_agent(){
   mkdir -m 0700 -p -- "/tmp/${service}"
   dir="${HOME}/.ssh/identities.d/${agent}"
   if ! test -d "${dir}"; then
-    echo "Directory not found: ${dir}" >&2
+    printf '%s\n' "Directory not found: ${dir}" >&2
     return 1
   fi
   dir="${dir##*/}"
@@ -48,7 +48,7 @@ add_agent(){
   keys="$(grep -sl -e "-----BEGIN OPENSSH PRIVATE KEY-----" \
           -- "${HOME}/.ssh/identities.d/${dir}"/* || true)"
   if test -z "${keys}"; then
-    echo "Directory has no key: ${dir}" >&2
+    printf '%s\n' "Directory has no key: ${dir}" >&2
     return 1
   fi
   SSH_AUTH_SOCK="${socket}" ssh-add -D 2>/dev/null || true
diff --git a/salt/sys-wireguard/files/admin/bin/qvm-wireguard b/salt/sys-wireguard/files/admin/bin/qvm-wireguard
--- a/salt/sys-wireguard/files/admin/bin/qvm-wireguard
+++ b/salt/sys-wireguard/files/admin/bin/qvm-wireguard
@@ -11,7 +11,7 @@ uid="$(id -u)"
 test "${uid}" = "0" || exec sudo "$0" "${@}"
 
 usage(){
-  echo "Usage: ${0##*/} [QUBE]"
+  printf '%s\n' "Usage: ${0##*/} [QUBE]"
   exit "${1:-1}"
 }
 
@@ -23,7 +23,7 @@ case "${1-}" in
 esac
 
 if ! qvm-check -q -- "${qube}" >/dev/null 2>&1; then
-  echo "Qube '${qube}' doesn't exist" >&2
+  printf '%s\n' "Qube '${qube}' doesn't exist" >&2
   usage 1
 fi
 
@@ -31,11 +31,11 @@ user_conf="/home/user/wireguard.conf"
 system_conf="/etc/wireguard/wireguard.conf"
 
 qvm-run "${qube}" -- "test -f ${user_conf}" || {
-  echo "File '${user_conf}' was not found" >&2
+  printf '%s\n' "File '${user_conf}' was not found" >&2
   if qvm-check -q --running -- "${qube}" >/dev/null 2>&1; then
     qvm-pause --verbose -- "${qube}"
   fi
-  echo "Firewalling ${qube} to drop all connections"
+  printf '%s\n' "Firewalling ${qube} to drop all connections"
   qvm-firewall --verbose -- "${qube}" reset
   qvm-firewall --verbose -- "${qube}" del --rule-no 0
   qvm-firewall --verbose -- "${qube}" add drop
@@ -51,7 +51,7 @@ qvm-run -u root "${qube}" -- "cp -- \"${user_conf}\" \"${system_conf}\""
 # shellcheck disable=SC2016
 endpoint="$(qvm-run -p -u root "${qube}" -- awk '/Endpoint/{print $3}' \
   "${system_conf}")"
-if echo "${endpoint}" | grep -qF -e "["; then
+if printf '%s\n' "${endpoint}" | grep -qF -e "["; then
   ip="${ip##[\[]}"
   ip="${ip%%\]*}"
   port="${endpoint##*:}"
@@ -61,7 +61,7 @@ else
 fi
 
 if test -z "${ip}" || test -z "${port}";then
-  echo "Endpoint (IP:Port) not found: ${system_conf}" >&2
+  printf '%s\n' "Endpoint (IP:Port) not found: ${system_conf}" >&2
   exit 1
 fi
 
@@ -69,7 +69,7 @@ if qvm-check -q --running -- "${qube}" >/dev/null 2>&1; then
   qvm-pause --verbose -- "${qube}"
 fi
 
-echo "Firewalling ${qube} to reach only '${ip}:${port}'"
+printf '%s\n' "Firewalling ${qube} to reach only '${ip}:${port}'"
 qvm-firewall --verbose -- "${qube}" reset
 qvm-firewall --verbose -- "${qube}" del --rule-no 0
 qvm-firewall --verbose -- "${qube}" add accept dsthost="${ip}" \
