style: limit line length per file extension
Editorconfig can only act based on file extension and path, not
attributes, it remains a mean only for multiple collaborators to use the
same configuration on their editor. When it is too restrictive, such as
not considering the file syntax, use a lint tool for the specific file
type instead of trusting editorconfig. Changes were made to increase
readability.

diff --git a/salt/dom0/files/bin/qvm-port-forward b/salt/dom0/files/bin/qvm-port-forward
--- a/salt/dom0/files/bin/qvm-port-forward
+++ b/salt/dom0/files/bin/qvm-port-forward
@@ -72,7 +72,10 @@ get_rule_handle(){
   qube="${1}"
   chain="${2}"
   rule="${3}"
-  run_qube "${qube}" "nft --handle --stateless list chain ip qubes ${chain} | tr -d '\"' | grep '^\s\+${rule} # handle ' | awk '{print \$NF}' | tr '\n' ' '" 2>/dev/null
+  run_qube "${qube}" -- \
+    "nft --handle --stateless list chain ip qubes ${chain} |
+    tr -d '\"' | grep '^\s\+${rule} # handle ' | awk '{print \$NF}' |
+    tr '\n' ' '" 2>/dev/null
 }
 
 delete_rule_handle(){
@@ -124,10 +127,15 @@ forward() {
   fi
 
   dnat_chain="custom-pf-${to_ip_escaped}"
-  dnat_rule="iifname ${dev} ip saddr ${lan_ip} ${proto} dport ${port} ct state established,related,new counter dnat to ${to_ip}"
+  dnat_rule="iifname ${dev} ip saddr ${lan_ip} ${proto} dport ${port} ct"
+  dnat_rule="${dnat_rule} state established,related,new counter dnat to"
+  dnat_rule="${dnat_rule} ${to_ip}"
   forward_chain="custom-forward"
-  forward_rule="iifname ${dev} ip saddr ${lan_ip} ip daddr ${to_ip} ${proto} dport ${port} ct state established,related,new counter accept"
-  full_rule="nft 'add chain ip qubes ${dnat_chain} { type nat hook prerouting priority filter +1; policy accept; }
+  forward_rule="iifname ${dev} ip saddr ${lan_ip} ip daddr ${to_ip} ${proto}"
+  forward_rule="${forward_rule} dport ${port} ct state"
+  forward_rule="${forward_rule} established,related,new counter accept"
+  dnat_policy="type nat hook prerouting priority filter +1; policy accept;"
+  full_rule="nft 'add chain ip qubes ${dnat_chain} { ${dnat_policy}
 add rule ip qubes ${dnat_chain} ${dnat_rule}
 add rule ip qubes ${forward_chain} ${forward_rule}'"
 
@@ -137,7 +145,8 @@ add rule ip qubes ${forward_chain} ${forward_rule}'"
     echo "info: ${from_qube}: deleting rules" >&2
     run_qube "${from_qube}" "rm -f ${hook}"
   else
-    echo "info: ${from_qube}: adding forward rule dev ${dev} saddr ${lan_ip} daddr ${to_ip}" >&2
+    msg="adding forward rule dev ${dev} saddr ${lan_ip} daddr ${to_ip}"
+    echo "info: ${from_qube}: ${msg}" >&2
     run_qube "${from_qube}" "${full_rule}"
 
     if test "${persistent}" = "1"; then
@@ -149,7 +158,9 @@ add rule ip qubes ${forward_chain} ${forward_rule}'"
 get_handle(){
   chain=\\\${1}
   rule=\\\${2}
-  nft --handle --stateless list chain ip qubes \\\${chain} | tr -d '\\\"' | grep '^\\\s\\\+\\\${rule} \\# handle ' | awk '{print \\\$NF}' | tr \\\"\\\n\\\" \\\" \\\"
+  nft --handle --stateless list chain ip qubes \\\${chain} | \\\
+    tr -d '\\\"' | grep '^\\\s\\\+\\\${rule} \\# handle ' | \\\
+    awk '{print \\\$NF}' | tr \\\"\\\n\\\" \\\" \\\"
 }
 
 forward_handle=\\\$(get_handle ${forward_chain} \\\"${forward_rule}\\\")
@@ -169,7 +180,8 @@ fi
 ${full_rule}"
 
       create_net_dir "${from_qube}"
-      run_qube "${from_qube}" "echo \"${full_rule}\" | tee \"${hook}\" >/dev/null"
+      run_qube "${from_qube}" \
+        "echo \"${full_rule}\" | tee \"${hook}\" >/dev/null"
       run_qube "${from_qube}" "chmod +x ${hook}"
     fi
   fi
@@ -181,7 +193,8 @@ input() {
   hook="${hook_prefix}${to_ip}-${proto}-${port}.sh"
   create_net_dir "${qube}"
 
-  custom_input_rule="${proto} dport ${port} ip daddr ${to_ip} ct state new counter accept"
+  custom_input_rule="${proto} dport ${port} ip daddr ${to_ip} ct state new"
+  custom_input_rule="${custom_input_rule} counter accept"
   input_rule="nft add rule ip qubes custom-input ${custom_input_rule}"
 
   delete_rule "${qube}" "custom-input" "${custom_input_rule}"
@@ -196,7 +209,9 @@ input() {
 get_handle(){
   chain=\\\${1}
   rule=\\\${2}
-  nft --handle --stateless list chain ip qubes \\\${chain} | tr -d '\\\"' | grep '^\\\s\\\+\\\${rule} \\# handle ' | awk '{print \\\$NF}' | tr \\\"\\\n\\\" \\\" \\\"
+  nft --handle --stateless list chain ip qubes \\\${chain} | \\\
+    tr -d '\\\"' | grep '^\\\s\\\+\\\${rule} \\# handle ' | \\\
+    awk '{print \\\$NF}' | tr \\\"\\\n\\\" \\\" \\\"
 }
 
 input_handle=\\\$(get_handle custom-input \\\"${custom_input_rule}\\\")
@@ -244,7 +259,7 @@ get_lan(){
 test_qvm_run(){
   qube="${1}"
   if ! run_qube "${qube}" echo "Test QUBESRPC" >/dev/null 2>&1; then
-    echo "error: ${qube}: service qubes.VMShell failed, use a different qube" >&2
+    echo "error: ${qube}: RPC qubes.VMShell failed, use a different qube" >&2
     exit 1
   fi
 }
@@ -267,7 +282,9 @@ recurse_netvms() {
 }
 
 usage() {
-  echo "Usage: ${0##*/} --action ACTION --qube QUBE --port PORT --proto PROTO [--persistent]
+  echo "Usage: ${0##*/} OPTIONS
+Option syntax:
+  --action ACTION --qube QUBE --port PORT --proto PROTO [--persistent]
 Options:
   -a, --action ACTION        add or delete a rule (add, del)
   -q, --qube QUBE            qube name which holds the service to be exposed
@@ -280,7 +297,7 @@ Example:
   ${0##*/} --action del --qube work --port 22 --proto tcp
   ${0##*/} --action del --qube work --port 444 --proto udp
 Note: Defaults to temporary rules
-Warn: Use of '--persistent' with disposable netvm saves the rule in the disposable template" >&2
+Warn: Persistent rules of disposable netvm are saved to its template" >&2
   exit 1
 }
 
@@ -322,7 +339,9 @@ hook_dir="/rw/config/network-hooks.d"
 hook_prefix="${hook_dir}/90-port-forward-"
 persistent=""
 
-if ! OPTS=$(getopt -o h,a:q:p:n:s --long help,action:,qube:,port:,proto:,persistent -n "${0}" -- "${@}"); then
+if ! OPTS=$(getopt -o h,a:q:p:n:s \
+  --long help,action:,qube:,port:,proto:,persistent -n "${0}" -- "${@}")
+then
   echo "An error occurred while parsing options." >&2
   exit 1
 fi
diff --git a/salt/sys-bitcoin/files/server/bin/bitcoin-rpcwhitelist-cookie b/salt/sys-bitcoin/files/server/bin/bitcoin-rpcwhitelist-cookie
--- a/salt/sys-bitcoin/files/server/bin/bitcoin-rpcwhitelist-cookie
+++ b/salt/sys-bitcoin/files/server/bin/bitcoin-rpcwhitelist-cookie
@@ -8,7 +8,8 @@ set -eu
 conf="${HOME}/.bitcoin/conf.d/cookie.conf"
 
 if ! systemctl is-active bitcoind >/dev/null 2>&1; then
-  echo "systemd service 'bitcoind' is not active, remote RPC cannot add crendtials" >&2
+  echo "systemd service 'bitcoind' is inactive" >&2
+  echo "remote RPC can't add crendetials" >&2
   exit 1
 fi
 
diff --git a/salt/sys-cacher/files/client/bin/apt-cacher-ng-repo b/salt/sys-cacher/files/client/bin/apt-cacher-ng-repo
--- a/salt/sys-cacher/files/client/bin/apt-cacher-ng-repo
+++ b/salt/sys-cacher/files/client/bin/apt-cacher-ng-repo
@@ -30,23 +30,27 @@ set_proxy_marker(){
 
   if ! grep -q "^${marker_begin}$" "${proxy_file}"; then
     if grep -q "^${marker_end}$" "${proxy_file}"; then
-      echo "Error: found marker ${marker_end_text} but not ${marker_begin_text} in ${proxy_file}" >&2
-      echo "Fix the file by either removing both markers or adding missing ones and retry" >&2
+      msg="found marker ${marker_end_text} but not ${marker_begin_text}"
+      msg="${msg} in ${proxy_file}."
+      msg="${msg} fix it by removing markers or adding missing ones and retry"
+      echo "Error: ${msg}" >&2
       exit 1
     fi
     cp "${proxy_file}" "${proxy_file}.qubes-orig"
     echo "${marker_begin}" | tee -a "${proxy_file}" >/dev/null
     echo "${marker_end}" | tee -a "${proxy_file}" >/dev/null
   elif ! grep -q "^${marker_end}$" "${proxy_file}"; then
-    echo "Error: found marker ${marker_begin_text} but not ${marker_end_text} in ${proxy_file}" >&2
-    echo "Fix the file by either removing both markers or adding missing ones and retry" >&2
+    msg="found marker ${marker_begin_text} but not ${marker_end_text}"
+    msg="${msg} in ${proxy_file}."
+    msg="${msg} fix it by removing markers or adding missing ones and retry"
+    echo "error: ${msg}" >&2
     exit 1
   fi
 
   proxy_tmp_file="$(mktemp)"
   cat >"${proxy_tmp_file}" <<EOF
-# The text between ${marker_begin_text} and ${marker_end_text} is automatically
-# generated by $0. All changes here will be overridden.
+# The text between ${marker_begin_text} and ${marker_end_text} is
+# automatically generated by $0. All changes here will be overridden.
 # You can override options after the ${marker_end_text}.
 ${proxy_options}
 EOF
@@ -76,7 +80,7 @@ check_netvm_cacher(){
   if test -f /var/run/qubes-service/netvm-cacher; then
     proxy_host="$(qubesdb-read /qubes-gateway)"
     if test -z "${proxy_host}"; then
-      echo "Error: service netvm-cacher enabled but netvm IP was not found" >&2
+      echo "Error: service netvm-cacher enabled but netvm IP not found" >&2
       return 1
     fi
   fi
@@ -120,9 +124,14 @@ EOF
 
     case "${action}" in
       install)
+        baseurl_search="baseurl\s*=\s*https://"
+        baseurl_repl="baseurl=http://HTTPS///"
+        meta_search="metalink\s*=\s*https://"
+        meta_repl="metalink=http://HTTPS///"
+        baseurl_expr="s|${baseurl_search}|${baseurl_repl}|w ${changes_file}"
+        meta_expr="s|${meta_search}|${meta_repl}|w ${changes_file}"
         find "${@}" -type f -exec sed -i \
-          -e "s|baseurl\s*=\s*https://|baseurl=http://HTTPS///|w ${changes_file}" \
-          -e "s|metalink\s*=\s*https://|metalink=http://HTTPS///|w ${changes_file}" \
+          -e "${baseurl_expr}" -e "${meta_expr}" \
         {} \+
 
         set --
@@ -136,16 +145,26 @@ EOF
         done
         test -n "${*}" || return 0
 
+        baseurl_search="^\s*#.*baseurl"
+        baseurl_repl="baseurl"
+        meta_search="^\s*metalink\s*=\s*"
+        meta_expr="#metalink="
+        baseurl_expr="s|${baseurl_search}|${baseurl_repl}|w ${changes_file}"
+        meta_expr="s|${meta_search}|${meta_repl}|w ${changes_file}"
         find "${@}" -type f -exec sed -i \
-          -e "s|^\s*#.*baseurl|baseurl|w ${changes_file}" \
-          -e "s|^\s*metalink\s*=\s*|#metalink=|w ${changes_file}" \
+          -e "${baseurl_expr}" -e "${meta_expr}" \
         {} \+
         ;;
 
       uninstall)
+        baseurl_search="baseurl\s*=\s*http://HTTPS///"
+        baseurl_repl="baseurl=https://"
+        meta_search="metalink\s*=\s*http://HTTPS///"
+        meta_repl="metalink=https://"
+        baseurl_expr="s|${baseurl_search}|${baseurl_repl}|w ${changes_file}"
+        meta_expr="s|${meta_search}|${meta_repl}|w ${changes_file}"
         find "${@}" -type f -exec sed -i \
-          -e "s|baseurl\s*=\s*http://HTTPS///|baseurl=https://|w ${changes_file}" \
-          -e "s|metalink\s*=\s*http://HTTPS///|metalink=https://|w ${changes_file}" \
+          -e "${baseurl_expr}" -e "${meta_expr}" \
         {} \+
 
         set --
@@ -194,16 +213,26 @@ EOF
 
     case "${action}" in
       install)
+        sources_search="URIs:\s*https://"
+        sources_repl="URIs: http://HTTPS///"
+        list_search="^\s*\(#*\)\s*deb\(.*\)https://"
+        list_repl="\1deb\2http://HTTPS///"
+        sources_expr="s|${sources_search}|${sources_repl}|w ${changes_file}"
+        list_expr="s|${list_search}|${list_repl}|w ${changes_file}"
         find "${@}" -type f -exec sed -i \
-          -e "s|URIs:\s*https://|URIs: http://HTTPS///|w ${changes_file}" \
-          -e "s|^\s*\(#*\)\s*deb\(.*\)https://|\1deb\2http://HTTPS///|w ${changes_file}" \
+          -e "${list_expr}" -e "${sources_expr}" \
         {} \+
         ;;
 
       uninstall)
+        sources_search="URIs:\s*http://HTTPS///"
+        sources_repl="URIs: https://"
+        list_search="^\s*\(#*\)\s*deb\(.*\)http://HTTPS///"
+        list_repl="\1deb\2https://"
+        sources_expr="s|${sources_search}|${sources_repl}|w ${changes_file}"
+        list_expr="s|${list_search}|${list_repl}|w ${changes_file}"
         find "${@}" -type f -exec sed -i \
-          -e "s|URIs:\s*http://HTTPS///|URIs: https://|w ${changes_file}" \
-          -e "s|^\s*\(#*\)\s*deb\(.*\)http://HTTPS///|\1deb\2https://|w ${changes_file}" \
+          -e "${list_expr}" -e "${sources_expr}" \
         {} \+
         ;;
     esac
@@ -242,21 +271,27 @@ EOF
 
     case "${action}" in
       install)
+        repo_search="Server\s*=\s*https://" \
+        repo_repl="Server = http://HTTPS///"
+        repo_regex="s|${repo_search}|${repo_repl}|w ${changes_file}"
         find "${@}" -type f -exec sed -i \
-          -e "s|Server\s*=\s*https://|Server = http://HTTPS///|w ${changes_file}" \
+          -e "${repo_regex}" \
         {} \+
         ;;
 
       uninstall)
+        repo_search="Server\s*=\s*http://HTTPS///"
+        repo_repl="Server = https://"
+        repo_regex="s|${repo_search}|${repo_repl}|w ${changes_file}"
         find "${@}" -type f -exec sed -i \
-          -e "s|Server\s*=\s*http://HTTPS///|Server = https://|w ${changes_file}" \
+          -e "${repo_regex}" \
         {} \+
         ;;
     esac
 
   else
     ## Gentoo: upstream does not have a good solution:
-    ##   https://wiki.gentoo.org/wiki/Local_distfiles_cache#Configuring_for_Gentoo
+    ## https://wiki.gentoo.org/wiki/Local_distfiles_cache#Configuring_for_Gentoo
     reject_os
   fi
 }
diff --git a/salt/sys-git/files/client/git-core/git-init-qrexec b/salt/sys-git/files/client/git-core/git-init-qrexec
--- a/salt/sys-git/files/client/git-core/git-init-qrexec
+++ b/salt/sys-git/files/client/git-core/git-init-qrexec
@@ -11,14 +11,16 @@ case "${GIT_TRACE_HELPER:-}" in
 esac
 
 usage(){
-  echo "Usage: ${helper} [<qube>] [<repository>]"
-  echo "Note: qube defaults to '@default' and repository to the current repository"
+  echo "Usage: ${helper} [<qube>] [<repository>]" >&2
+  echo "Note: qube defaults to @default" >&2
+  echo "Note: repository defaults to current working repository" >&2
   exit 1
 }
 
 is_git_repo(){
   if ! git rev-parse --show-toplevel >/dev/null 2>&1; then
-    echo "Error: Either run from inside a git repository or provide it as an argument" >&2
+    echo "Error: Current working directory is not in a git repository" >&2
+    echo "Error: Run from a repository or pass the name as an argument" >&2
     usage
   fi
 }
@@ -49,7 +51,8 @@ elif command -v qrexec-client >/dev/null; then
     die "Qube doesn't exist: '${authority}'"
   fi
   qvm-start --skip-if-running -- "${authority}"
-  exec qrexec-client -tT -d "${authority}" -- "DEFAULT:QUBESRPC ${rpc_cmd} dom0"
+  rpc_cmd="DEFAULT:QUBESRPC ${rpc_cmd} dom0"
+  exec qrexec-client -tT -d "${authority}" -- "${rpc_cmd}"
 fi
 
 die "Qrexec programs not found: qrexec-client-vm, qrexec-client"
