test

diff --git a/qusal/sys-ssh-agent/files/server/bin/qvm-ssh-agent b/qusal/sys-ssh-agent/files/server/bin/qvm-ssh-agent
--- a/qusal/sys-ssh-agent/files/server/bin/qvm-ssh-agent
+++ b/qusal/sys-ssh-agent/files/server/bin/qvm-ssh-agent
@@ -6,71 +6,71 @@
 
 set -eu
 
-sock_dir="qubes-ssh-agent"
-service="${sock_dir}-sock"
+service="qubes-ssh-agent"
 
 usage(){
-  echo "Usage: ${0##*/} [ls|key] [<AGENT>]
+  echo "Usage: ${0##*/} [ls|add] <AGENT>
   ls: list agent(s)
-  key: add keys to agent(s)
-If agent is not specified, action is taken on all agents.
+  add: add keys to agent(s)
+  reload: reload/readd keys from agent(s)
 Example:
-  ${0##*/} ls           # list all agents
-  ${0##*/} ls work      # list the work agent and its keys
-  ${0##*/} key          # add keys for each agent
-  ${0##*/} key work     # add keys for the work agent"
+  ${0##*/} ls work      # list the work agent keys
+  ${0##*/} add work     # add keys to the work agent
+  ${0##*/} reload work  # reload/readd keys from the work agent"
   exit 1
 }
 
 ls_agent(){
-  echo "Systemd user units:"
-  # shellcheck disable=SC2086
-  systemctl --user --no-pager list-units ${service}@$agent.service \
-    | grep "${service}@.*\.service" | sed "s/^[[:space:]]*//"
-  echo
-  for socket in /tmp/${sock_dir}/$agent.sock; do
-    test -S "$socket" || continue
-    agent="$(echo "$socket" | sed "s|.*${sock_dir}/||;s/\.sock//")"
-    echo "Agent: ($agent) $socket"
-    SSH_AUTH_SOCK="$socket" ssh-add -l || true
-    echo
+  socket="/tmp/${service}/$agent.sock"
+  test -S "$socket" || return 1
+  agent="$(echo "$socket" | sed "s|.*${service}/||;s/\.sock//")"
+  echo "Agent: ($agent) $socket"
+  SSH_AUTH_SOCK="$socket" ssh-add -l || true
+}
+
+add_agent(){
+  # shellcheck disable=SC2174
+  mkdir -m 0700 -p "/tmp/${service}"
+  dir="$HOME/.ssh/identities.d/${agent}"
+  if ! test -d "$dir"; then
+    echo "Directory not found: $dir" >&2
+    return 1
+  fi
+  dir="${dir##*/}"
+  socket="/tmp/${service}/${dir}.sock"
+  if ! test -S "$socket"; then
+    reload_agent=1
+    ssh-agent -a "/tmp/${service}/${agent}.sock"
+  fi
+  if ! test "${reload_agent}" = "1"; then
+    return
+  fi
+  keys="$(grep -sl -- "-----BEGIN OPENSSH PRIVATE KEY-----" \
+          "$HOME/.ssh/identities.d/$dir"/* || true)"
+  if test -z "$keys"; then
+    echo "Directory has no key: $dir" >&2
+    return 1
+  fi
+  SSH_AUTH_SOCK="$socket" ssh-add -D 2>/dev/null || true
+  for k in $(printf '%s\n' "$keys"); do
+    test -f "$k" || continue
+    ssh_add_option=""
+    if test -f "$k.ssh-add-option"; then
+      ssh_add_option="$(cat "$k.ssh-add-option")"
+    fi
+    # shellcheck disable=SC2086
+    SSH_AUTH_SOCK="$socket" ssh-add $ssh_add_option "$k"
   done
 }
 
-add_key(){
-  for dir in $HOME/.ssh/identities.d/$agent; do
-    test -d "$dir" || continue
-    dir="${dir##*/}"
-    socket="/tmp/${sock_dir}/${dir}.sock"
-    test -S "$socket" || continue
-    keys="$(grep -sl -- "-----BEGIN OPENSSH PRIVATE KEY-----" \
-            "$HOME/.ssh/identities.d/$dir"/* || true)"
-    test -n "$keys" || continue
-    echo "Agent: ($dir) $socket"
-    SSH_AUTH_SOCK="$socket" ssh-add -D 2>/dev/null || true
-    for k in $(printf '%s\n' "$keys"); do
-      test -f "$k" || continue
-      ssh_add_option=""
-      if test -f "$k.ssh-add-option"; then
-        ssh_add_option="$(cat "$k.ssh-add-option")"
-      fi
-      # shellcheck disable=SC2086
-      SSH_AUTH_SOCK="$socket" ssh-add $ssh_add_option "$k"
-    done
-    echo
-  done
-}
-
-test -z "${1-}" && usage
+test -z "${2-}" && usage
 action="${1-}"
 agent="${2-}"
-
-case "$action" in
-  ls|key) agent="${agent:-*}";;
-  *) usage;;
-esac
+reload_agent=""
 
 case "$action" in
   ls) ls_agent;;
-  key) add_key;;
+  add) add_agent;;
+  reload) reload_agent="1"; add_agent;;
+  *) usage;;
 esac
